coke_small			.75		can
coke_small			.75		can
coke_small			.75		can
coke_small			.75		can
coke_small			.75		can
diet_coke_small		.75		can
diet_coke_small		.75		can
diet_coke_small		.75		can
diet_coke_small		.75		can
diet_coke_small		.75		can
sprite_small		.75		can
sprite_small		.75		can
sprite_small		.75		can
sprite_small		.75		can
sprite_small		.75		can
seven-up_small		.75		can
seven-up_small		.75		can
seven-up_small		.75		can
seven-up_small		.75		can
seven-up_small		.75		can
mtn_dew_small		.75		can
mtn_dew_small		.75		can
mtn_dew_small		.75		can
mtn_dew_small		.75		can
mtn_dew_small		.75		can
dr.pepper_small		.75		can
dr.pepper_small		.75		can
dr.pepper_small		.75		can
dr.pepper_small		.75		can
dr.pepper_small		.75		can
fanta_orange_small	.75		can
fanta_orange_small	.75		can
fanta_orange_small	.75		can
fanta_orange_small	.75		can
fanta_orange_small	.75		can
fanta_grape_small	.75		can
fanta_grape_small	.75		can
fanta_grape_small	.75		can
fanta_grape_small	.75		can
fanta_grape_small	.75		can
coke_lg				1.25	bottle
coke_lg				1.25	bottle
coke_lg				1.25	bottle
coke_lg				1.25	bottle
coke_lg				1.25	bottle
diet_coke_lg		1.25	bottle
diet_coke_lg		1.25	bottle
diet_coke_lg		1.25	bottle
diet_coke_lg		1.25	bottle
diet_coke_lg		1.25	bottle
sprite_lg			1.25	bottle
sprite_lg			1.25	bottle
sprite_lg			1.25	bottle
sprite_lg			1.25	bottle
sprite_lg			1.25	bottle
seven-up_lg			1.25	bottle
seven-up_lg			1.25	bottle
seven-up_lg			1.25	bottle
seven-up_lg			1.25	bottle
seven-up_lg			1.25	bottle
mtn_dew_lg			1.25	bottle
mtn_dew_lg			1.25	bottle
mtn_dew_lg			1.25	bottle
mtn_dew_lg			1.25	bottle
mtn_dew_lg			1.25	bottle
dr.pepper_lg		1.25	bottle
dr.pepper_lg		1.25	bottle
dr.pepper_lg		1.25	bottle
dr.pepper_lg		1.25	bottle
dr.pepper_lg		1.25	bottle
fanta_orange_lg		1.25	bottle
fanta_orange_lg		1.25	bottle
fanta_orange_lg		1.25	bottle
fanta_orange_lg		1.25	bottle
fanta_orange_lg		1.25	bottle
fanta_grape_lg		1.25	bottle
fanta_grape_lg		1.25	bottle
fanta_grape_lg		1.25	bottle
fanta_grape_lg		1.25	bottle
fanta_grape_lg		1.25	bottle